project = "demo"

[app]

name = "demo"

[app.build]
provider = "docker"

[app.build.registry]
host = "ghcr.io/forgeron-io/nextjs-demo"

[app.deploy]
provider = "terraform"
path = "./terraform"
# provider = "kubernetes"
# port = 3000
# host = "demo.martin-paucot.fr"
